config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/publitas_embed", to: "custom_pages#publitas_embed", as: "publitas_embed"

  resources :products do
    get :catalogue_popover, on: :member
    member do
      post :add_to_cart
      delete :remove_from_cart
    end
  end

  resources :carts, only: [:show]
  get '/my_cart', to: 'carts#my_cart', as: 'my_cart'
  get '/popover_cart', to: 'carts#popover_cart', as: :popover_cart

  resources :cart_items, only: [:update, :destroy]

  post '/csp-violation-report-endpoint', to: 'csp_reports#create'

  root to: 'custom_pages#publitas_embed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image

  def image_url
    Rails.application.routes.url_helpers.rails_blob_path(self.image, only_path: true) if self.image.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_cart

  private

  def current_cart
    # Find the cart by the stored session ID or create a new one if none exists
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end

  def cart_count
    current_cart.cart_items.sum(&:quantity)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find(params[:id])
    @cart_item.update(quantity: params[:cart_item][:quantity])
    if @cart_item.quantity == 0
      @cart_item.destroy
    end
    @cart_count = cart_count

    respond_to do |format|
      format.js
      format.html { redirect_to my_cart_path, layout: false }
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end

  def my_cart
    @cart = current_cart
    render "show"
  end

  def popover_cart
    @cart = current_cart
    render "popover_cart", layout: false
  end

  def update_quantity
    @cart = current_cart
    @cart_item = @cart.cart_items.find(params[:id])
    redirect_to my_cart_path
  end


end

app/controllers/custom_pages_controller.rb
class CustomPagesController < ApplicationController

  def publitas_embed
    @cart_count = cart_count
    render "publitas_embed"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:add_to_cart]
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def catalogue_popover
    @product = Product.find(params[:id])
    @product_count = current_cart.cart_items.where(product_id: @product.id).sum(:quantity)
    render layout: false
  end


  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new  # Ensure you're rendering the 'new' view on failure
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit  # Ensure you're rendering the 'edit' view on failure
    end
  end

  def add_to_cart
    Rails.logger.info "============ request_format: #{request.format} ================="
    cart = current_cart
    product = Product.find(params[:id])
    cart_item = cart.cart_items.find_or_initialize_by(product: product)
    cart_item.quantity ||= 0
    cart_item.quantity += 1
    cart_item.save

    @product_count = current_cart.cart_items.where(product_id: product.id).sum(:quantity)
    @cart_count = cart_count

    respond_to do |format|
      format.js
      format.html { redirect_to cart_path(current_cart) }
    end
  end

  def remove_from_cart
    cart = current_cart
    product = Product.find(params[:id])
    cart_item = cart.cart_items.find_by(product: product)
    cart_item.destroy if cart_item.present?
    respond_to do |format|
      format.js
      format.html { redirect_to cart_path(current_cart) }
    end
  end


  private
  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart_items/update.js.erb
// update publitas cart count

<% if @cart_count  %>
// update publitas cart count
parent.postMessage( JSON.stringify(['cartContentChanged', {
    numItems: <%= j @cart_count %>
}]), "https://view.publitas.com/" );
<% end %>

// To reload the view
location.reload();

app/views/carts/_cart_list.html.erb
<div class="basket">
  <div class="basket-labels">
    <ul>
      <li class="item item-heading">Item</li>
      <li class="price">Price</li>
      <li class="quantity">Quantity</li>
      <li class="subtotal">Subtotal</li>
    </ul>
  </div>
  <% @cart.cart_items.each do |item| %>
    <div class="basket-product">
      <div class="item">
        <div class="product-image">
          <%= image_tag item.product.image_url, alt: item.product.title, class: "product-frame" %>
        </div>
        <div class="product-details">
          <h1><strong><span class="item-quantity">4</span> x Eliza J</strong><%= item.product.title %></h1>
          <p><strong>Navy, Size 18</strong></p>
          <p>Product Code - 232321939</p>
        </div>
      </div>
      <div class="price">26.00</div>
      <div class="quantity">
        <input type="number" value="4" min="1" class="quantity-field">
      </div>
      <div class="subtotal">104.00</div>
      <div class="remove">
        <button>Remove</button>
      </div>
    </div>
  <% end %>
</div>

app/views/carts/_cart_side_bar.html.erb
<aside>
  <div class="summary">
    <div class="summary-total-items"><span class="total-items"></span> Items in your Bag</div>
    <div class="summary-total">
      <div class="total-title">Total</div>
      <div class="total-value final-value" id="basket-total"><%= number_to_currency(@cart.cart_items.sum { |item| item.quantity*item.product.price }, unit: "€") %></div>
    </div>
    <div class="summary-checkout">
      <button class="checkout-cta">Go to Secure Checkout</button>
    </div>
  </div>
</aside>

app/views/carts/popover_cart.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<h1>Shopping Cart</h1>
<main>
  <div class="basket">
    <div class="basket-labels">
      <ul>
        <li class="item item-heading">Item</li>
        <li class="price">Price</li>
        <li class="quantity">Quantity</li>
        <li class="subtotal">Subtotal</li>
      </ul>
    </div>
    <% @cart.cart_items.each do |item| %>
      <div class="basket-product">
        <div class="item" id="cart_item_<%= item.id %>">
          <div class="cart-product-image">
            <%= image_tag item.product.image_url, alt: item.product.title, class: "product-frame" %>
          </div>
          <div class="product-details">
            <h1><strong><span class="item-quantity"><%= item.quantity %> x </span></strong><%= item.product.title %></h1>
            <div class="price"><%= number_to_currency(item.product.price, unit: "€") %></div>
            <% if item.quantity %>
              <%= form_for item, method: :patch, remote: true, class: "update-quantity" do |f| %>
                <div class="quantity">
                  <%= f.number_field :quantity, value: item.quantity, min: 1, class: "quantity-field" %>
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                  <%= f.submit "Update Quantity", class: "action-button" %>
                </div>
              <% end %>
            <% end %>
            <div class="subtotal"><%= number_to_currency((item.product.price * item.quantity), unit: "€") %></div>
          </div>
        </div>
        <div class="remove">
          <%= button_to "Remove",  remove_from_cart_product_path(item.product), method: :delete, remote: true, class: "action-button" %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render partial: "cart_side_bar", locals: { cart: @cart } %>
</main>

app/views/carts/show.html.erb
<%= javascript_pack_tag 'shoppingCart', 'data-turbolinks-track': 'reload' %>
<main>
  <%= render partial: "cart_list", locals: { cart: @cart } %>
  <%= render partial: "cart_side_bar", locals: { cart: @cart } %>
</main>

app/views/custom_pages/publitas_embed.html.erb
<%#= javascript_pack_tag 'sendCountToPublitasCart' %>
<div id="publitas-embed-scwirwgmk8" ></div>
<script data-cfasync="false" data-height="600"
        data-publication="https://view.publitas.com/publitas-owen-thomas/clothes_shop_catalogue/"
        data-publication-aspect-ratio="0.5625879043600562"
        data-responsive="true"
        data-width="undefined"
        data-wrapper-id="publitas-embed-scwirwgmk8"
        publitas-embed src="https://view.publitas.com/embed.js"
        type="text/javascript">
</script>

app/views/layouts/_nav_bar.html.erb
<nav class="main-nav">
  <div class="nav-content">
    <%= link_to 'Home', root_path, class: "nav-link" %>
    <%= link_to 'Shop', products_path, class: "nav-link" %>
    <%= link_to 'About', "https://www.google.ie", class: "nav-link" %>
    <%= link_to 'View Catalogue', publitas_embed_path , class: "nav-link" %>
    <div class="cart">
      <%= link_to cart_path(current_cart), class: "nav-link" do %>
        <i class="cart-icon">🛒</i>
        <span id="cart-count"><%= current_cart.cart_items.sum(&:quantity)%></span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PublitasIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'topMessageListener', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'shoppingCart', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/products/_product_card.html.erb
<div class="product-card">
  <% if product.image_url.present? %>
    <%= image_tag product.image_url, alt: product.title, class: "product-image" %>
  <% end %>
  <h2 class="product-title"><%= product.title %></h2>
  <p class="product-price"><%= number_to_currency(product.price) %></p>
</div>

app/views/products/add_to_cart.js.erb
<% if @cart_count %>
window.top.document.getElementById("cart-count").innerHTML = "<%= j @cart_count %>";
// update count of this product in cart
document.getElementById("products-in-cart").innerHTML = "<%= j @product_count %> in your cart"
// update publitas cart count
parent.postMessage( JSON.stringify(['cartContentChanged', {
    numItems: <%= j @cart_count %>
}]), "https://view.publitas.com/" );
<% end %>

function showBanner() {
    var banner = document.getElementById('banner');

    // Display the banner
    banner.classList.remove('hidden');
    banner.classList.remove('fade-out');

    // After 3 seconds, fade out the banner
    setTimeout(function() {
        banner.classList.add('fade-out');

        // After the transition ends (1 second, as set in the CSS), hide the banner
        setTimeout(function() {
            banner.classList.add('hidden');
        }, 1000);
    }, 3000);
}
showBanner();

app/views/products/catalogue_popover.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_pack_tag "application", "data-turbo-track": "reload" %>

<div id="banner" class="hidden">Product added to cart</div>
<div class="card">
  <div class="photo">
    <img class="product-image" src=<%= @product.image_url %> alt=<%= @product.title %> />
  </div>
  <div class="product-description">
    <h2><%= @product.title %></h2>
    <h4></h4>
    <h1><%= number_to_currency(@product.price, unit: "€") %></h1>
    <p><%= @product.description %></p>
    <%= form_tag add_to_cart_product_path(@product), method: :post, remote: true, class: 'button-form' do %>
      <%= submit_tag 'Add to Cart', class: 'action-button', id:"add-to-cart-button" %>
      <% if @product_count %>
        <span id="products-in-cart"><%= @product_count %> in your cart</span>
        <span id="products-in-cart"><%= link_to "View Cart", popover_cart_path, class: "button" %></span>
      <% end %>
    <% end %>
    <%#= button_to 'Add to Cart', add_to_cart_product_path(@product), method: :post, remote: true, class: 'button', id:"add-to-cart-button" %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="products-grid">
  <% @products.each do |product| %>
    <%= render 'product_card', product: product %>
    <%= button_to "Add to Cart", add_to_cart_product_path(product), remote: true, class: "button" %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/remove_from_cart.js.erb
console.log("Remove from cart <%= @product %>");
// To reload the view
location.reload();

app/views/products/show.html.erb
<%= render 'product_card', product: @product %>
<%= button_to "Add to Cart", add_to_cart_product_path(@product) %>